import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  generateJobInterviewQuestions,
  getJob,
  listJobs,
} from "../services/backend";
import { useAuth } from "../context/AuthContext";

interface JobSummary {
  id: number;
  title: string;
  company_name?: string;
  jd_text?: string;
  coverage_threshold?: number;
  status?: string;
  has_attachment?: boolean;
  attachment_name?: string | null;
}

const InterviewQuestionsPage: React.FC = () => {
  const { user } = useAuth();
  const [jobs, setJobs] = useState<JobSummary[]>([]);
  const [jobsLoading, setJobsLoading] = useState(false);
  const [jobsError, setJobsError] = useState<string | null>(null);
  const [selectedJobId, setSelectedJobId] = useState<number | null>(null);
  const [selectedJob, setSelectedJob] = useState<JobSummary | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);

  const [domain, setDomain] = useState<"behavioral" | "technical">(
    "behavioral"
  );
  const [jdSupplement, setJdSupplement] = useState("");
  const [jdFile, setJdFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const [generating, setGenerating] = useState(false);
  const [resultQuestions, setResultQuestions] = useState<string[]>([]);
  const [resultInfo, setResultInfo] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setJobsLoading(true);
    setJobsError(null);
    listJobs()
      .then((res) => {
        const list: JobSummary[] = Array.isArray(res.data) ? res.data : [];
        setJobs(list);
        if (list.length > 0) {
          setSelectedJobId(list[0].id);
        }
      })
      .catch((err) => {
        setJobsError(
          err?.response?.data?.detail ||
            "Unable to load job list. Please try again."
        );
      })
      .finally(() => setJobsLoading(false));
  }, []);

  useEffect(() => {
    if (!selectedJobId) {
      setSelectedJob(null);
      return;
    }
    const cached = jobs.find((item) => item.id === selectedJobId);
    if (cached && cached.jd_text) {
      setSelectedJob(cached);
      return;
    }
    setDetailLoading(true);
    getJob(selectedJobId)
      .then((res) => {
        setSelectedJob(res.data || null);
      })
      .catch(() => {
        setSelectedJob(cached || null);
      })
      .finally(() => setDetailLoading(false));
  }, [selectedJobId, jobs]);

  const hasStoredJd = useMemo(
    () => Boolean((selectedJob?.jd_text || "").trim()),
    [selectedJob?.jd_text]
  );

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] || null;
    setJdFile(file);
  };

  const clearFile = () => {
    setJdFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleGenerate = async () => {
    if (!selectedJobId) {
      setError("Please select a job before creating a question.");
      return;
    }
    if (!hasStoredJd && !jdSupplement.trim() && !jdFile) {
      setError(
        "No JD content available. Please enter or upload JD for AI processing."
      );
      return;
    }
    setError(null);
    setResultInfo(null);
    setGenerating(true);
    try {
      const res = await generateJobInterviewQuestions(selectedJobId, {
        domain,
        jd_text: jdSupplement,
        jd_file: jdFile ?? undefined,
      });
      const data = res.data;
      const list = Array.isArray(data?.questions) ? data.questions : [];
      setResultQuestions(list);
      if (data?.source && data.source !== "gemini") {
        setResultInfo(
          "Gemini is temporarily unavailable, questions are generated by default."
        );
      } else if (list.length > 0) {
        setResultInfo("Questions have been generated by Gemini.");
      } else {
        setResultInfo("AI has not returned any questions. Please try again.");
      }
    } catch (err: any) {
      setResultQuestions([]);
      setError(
        err?.response?.data?.detail ||
          "Unable to create interview question. Please try again later."
      );
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="max-w-5xl p-6 mx-auto space-y-6">
      <header className="space-y-2">
        <h1 className="text-2xl font-semibold text-slate-900">
          Create interview questions
        </h1>
        <p className="text-sm text-slate-600">
          Generate up to 5 questions based on the JD. You can supplement the
          description or upload a file for Gemini to read.
        </p>
        {user?.role === "employer" && (
          <p className="text-xs text-slate-500">
            Tip: Each time you regenerate, the latest version of the JD for the
            job will be used.
          </p>
        )}
      </header>

      {jobsError && (
        <div className="px-4 py-2 text-sm border rounded border-rose-200 bg-rose-50 text-rose-600">
          {jobsError}
        </div>
      )}

      <section className="p-6 space-y-4 bg-white border shadow-sm rounded-xl border-slate-200">
        <div className="grid gap-3 md:grid-cols-2">
          <div className="space-y-2">
            <label
              htmlFor="job-select"
              className="block text-sm font-medium text-slate-700"
            >
              Select job
            </label>
            <select
              id="job-select"
              className="w-full px-3 py-2 text-sm border rounded-lg border-slate-300 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"
              value={selectedJobId ?? ""}
              onChange={(e) => {
                const value = Number(e.target.value);
                setSelectedJobId(Number.isNaN(value) ? null : value);
                setResultQuestions([]);
              }}
              disabled={jobsLoading || generating}
            >
              {jobs.map((job) => (
                <option key={job.id} value={job.id}>
                  {job.title} {job.company_name ? `- ${job.company_name}` : ""}
                </option>
              ))}
              {jobs.length === 0 && <option value="">(No job)</option>}
            </select>
          </div>
          <div className="space-y-2">
            <label
              htmlFor="domain-select"
              className="block text-sm font-medium text-slate-700"
            >
              Question group
            </label>
            <select
              id="domain-select"
              className="w-full px-3 py-2 text-sm border rounded-lg border-slate-300 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"
              value={domain}
              onChange={(e) =>
                setDomain(
                  e.target.value === "technical" ? "technical" : "behavioral"
                )
              }
              disabled={generating}
            >
              <option value="behavioral">Behavioral</option>
              <option value="technical">Technical</option>
            </select>
          </div>
        </div>

        <div className="space-y-2">
          <label className="text-sm font-medium text-slate-700">
            JD currently available
          </label>
          <div className="p-3 overflow-y-auto text-xs whitespace-pre-wrap border rounded-lg border-slate-200 bg-slate-50 text-slate-700 max-h-48">
            {detailLoading
              ? "Loading..."
              : hasStoredJd
              ? selectedJob?.jd_text
              : "(There is no JD text saved in the system.)"}
          </div>
        </div>

        <div className="space-y-2">
          <label
            htmlFor="jd-supplement"
            className="block text-sm font-medium text-slate-700"
          >
            Add JD description (optional)
          </label>
          <textarea
            id="jd-supplement"
            rows={6}
            className="w-full px-3 py-2 text-sm border rounded-lg border-slate-300 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"
            placeholder="Add detailed requirements, team descriptions or special skills..."
            value={jdSupplement}
            onChange={(e) => setJdSupplement(e.target.value)}
            disabled={generating}
          />
          <p className="text-xs text-slate-500">
            This content will be appended to the original JD before sending to
            AI.
          </p>
        </div>

        <div className="space-y-2">
          <label
            htmlFor="jd-file"
            className="block text-sm font-medium text-slate-700"
          >
            Upload JD file (optional)
          </label>
          <input
            id="jd-file"
            type="file"
            ref={fileInputRef}
            accept=".pdf,.doc,.docx,.txt,.md,.rtf"
            className="text-sm"
            onChange={handleFileChange}
            disabled={generating}
          />
          {jdFile ? (
            <div className="flex items-center gap-2 text-xs text-slate-600">
              <span className="truncate">{jdFile.name}</span>
              <button
                type="button"
                className="font-medium text-rose-500 hover:underline"
                onClick={clearFile}
                disabled={generating}
              >
                Remove file
              </button>
            </div>
          ) : (
            <p className="text-xs text-slate-400">
              Optional. Supports PDF, DOC, DOCX, TXT, RTF.
            </p>
          )}
        </div>

        {error && (
          <div className="px-4 py-2 text-sm border rounded border-rose-200 bg-rose-50 text-rose-600">
            {error}
          </div>
        )}
        {resultInfo && (
          <div className="px-4 py-2 text-sm text-blue-700 border border-blue-200 rounded bg-blue-50">
            {resultInfo}
          </div>
        )}

        <div className="flex items-center gap-3">
          <button
            type="button"
            className="inline-flex items-center px-4 py-2 text-sm font-semibold text-white transition bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-60"
            onClick={handleGenerate}
            disabled={generating || jobsLoading}
          >
            {generating ? "Creating question..." : "Create 5 questions"}
          </button>
          {resultQuestions.length > 0 && (
            <span className="text-xs text-slate-500">
              Created {resultQuestions.length} questions.
            </span>
          )}
        </div>
      </section>

      {resultQuestions.length > 0 && (
        <section className="p-6 space-y-2 bg-white border shadow-sm rounded-xl border-slate-200">
          <h2 className="text-lg font-semibold text-slate-900">
            List of questions
          </h2>
          <div className="space-y-3 text-sm text-slate-700">
            {resultQuestions.map((question, idx) => (
              <div
                key={`ai-question-${idx}`}
                className="flex items-start gap-3 px-4 py-3 border rounded-lg border-slate-200 bg-slate-50"
              >
                <span className="text-sm font-semibold text-slate-500">
                  {idx + 1}.
                </span>
                <p className="leading-relaxed">{question}</p>
              </div>
            ))}
          </div>
        </section>
      )}
    </div>
  );
};

export default InterviewQuestionsPage;
